### ISSUE TITLE
JCenter Deprecation

### ISSUE THREAD

**Issue by barnhill** [google/flexbox-layout#570] opened 2021-02-10 02:36 UTC
- [x] I have searched [existing issues](https://github.com/google/flexbox-layout/issues) and confirmed this is not a duplicate

## Issues and steps to reproduce
Wait till May 1 and this artifact will no longer be available on JCenter because JCenter is shutting down

## Expected behavior
This library will be available on Maven Central or googles own maven repo

## Version of the flexbox library
2.0.1

## Link to code
https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/

**Comment by thagikura** [comment] 2021-02-10 03:31
This is duplicate of #566.

**Closed by thagikura** 2021-02-10 03:31 UTC

**Comment by barnhill** [comment] 2021-02-10 04:26
:( How did I miss that.  Sorry about the dupe and thanks for the prompt response.
