### ISSUE TITLE
Move project to another repository

### ISSUE THREAD

**Issue by MenosGrante** [google/flexbox-layout#575] opened 2021-05-05 12:21 UTC
- [+] I have searched [existing issues](https://github.com/google/flexbox-layout/issues) and confirmed this is not a duplicate

Since jcenter is going to be shut down + Intellij IDEA/Android Studio already marking jcenter as deprecated/should-be-removed I guess it is time to think about moving it to another repository.

**Comment by CoreFloDev** [comment] 2021-05-06 09:56
Yes I got the same issue with intercom that depends on this repository

**Comment by MGaetan89** [comment] 2021-05-06 10:02
Duplicate of https://github.com/google/flexbox-layout/issues/566

**Comment by thagikura** [comment] 2021-05-17 12:41
Let me close this since it's a duplicate of #566

**Closed by thagikura** 2021-05-17 12:41 UTC
