### ISSUE TITLE
The first line disappears

### ISSUE THREAD

**Issue by xiaozhuge007** [google/flexbox-layout#228] opened 2017-03-17 09:37 UTC
Slide first line disappear  @link FlexboxLayoutManager

**Comment by thagikura** [comment] 2017-03-17 09:41
I think this is duplicate of #206 is that correct?

**Comment by justplay1** [comment] 2017-03-17 14:47
@thagikura I also have this bug, it's not a problem with scrollToPosition

**Comment by xiaozhuge007** [comment] 2017-03-20 00:50
@thagikura Sliding occurs when the first line of item is less than second lines
CatGallery Demo has the same problem and the first line will disappear

**Comment by xiaozhuge007** [comment] 2017-03-20 00:51
If the first line of item is greater than second lines, this bug will not appear

**Comment by thagikura** [comment] 2017-03-23 05:34
Reproduced it on my end. Taking a look.

Thanks for reporting the issue!

**Closed** 2017-03-23 08:13 UTC
Labels: bug

**Comment by thagikura** [comment] 2017-03-23 08:57
Fixed by #234

**Comment by justplay1** [comment] 2017-03-24 12:03
@thagikura When release this fix?

**Comment by thagikura** [comment] 2017-03-24 13:52
@justplay1 hopefully next week.
