### ISSUE TITLE
FlexboxLayoutManager doesn't work with payloads.

### ISSUE THREAD

**Issue by stephanenicolas** [google/flexbox-layout#297] opened 2017-06-13 00:57 UTC
- [x] I have searched [existing issues](https://github.com/google/flexbox-layout/issues) and confirmed this is not a duplicate

## Issues and steps to reproduce
FlexboxLayoutManager doesn't work with payloads. I would be glad to change an example to show the bug.

## Expected behavior
The overload of the bind method for the view holder that takes a payload as an extra param is never called when using a payload for the change. Hence the view holder is never refreshed, but it should.

## Version of the flexbox library
0.3.0-alpha3

## Link to code
I didn't do it yet. I just wanted to check if this is a new issue and if you need an example. If so, I can setup an example from a flexbox sample quickly.

**Comment by thagikura** [comment] 2017-06-13 02:23
Hi @stephanenicolas,

Thanks for the report. This is not a duplicate, it's really appreciated if you can link to the sample project or code that can reproduce the issue. Thanks!

**Comment by stephanenicolas** [comment] 2017-06-13 05:54
Here is the code @thagikura : https://github.com/google/flexbox-layout/pull/298

It's not a super simple example but I think you will get the point:
* you must use the recycler view mode in the demo playground app
* if you use a linear layout manager, it works well (I can add 3 items, then the + button changes the text of the last item)
* if you use the flexbox layout,`onBindViewHolder` with a payload is never called, the last button never increments.
* if you remove the payload in the call to `motifyItemChanged`, it works with the flexboxlayout manager, and calls the `onBindViewHolder` but without the payload param.

Is that clear enough for you ?

**Comment by stephanenicolas** [comment] 2017-06-13 05:59
I think the problem is that the adapter marks views as "not dirty anymore" too soon. Also, I am not sure that the cache of views is not an issue as well. But honestly, I didn't look that much at the cause of the issue. 

We would sooooo much appreciate a quick fix, we are experimenting a lot with our RV layout managers these days and we would love to use the flexbox layout. 
Do you know if we can expect the layout manager to be officially part of the SDK at some point ?

**Comment by thagikura** [comment] 2017-06-13 07:55
Thanks for the code to reproduce the issue! I was able to reproduce it, let me take a look.

Also thanks for your interest in the FlexboxLayoutManager, I expect I spot the issue not too long.
Regarding if FlexboxLayoutManager becomes part of the official SDK, it isn't planned at this moment.

**Comment by thagikura** [comment] 2017-06-13 10:42
I spotted the issue and sent a #299 to fix this.

As explained in the PR, the issue happened because FlexboxLayoutManager returned the scrapped views when it should be returned from RecyclerView (it's also through the scrapped views though).

**Comment by thagikura** [comment] 2017-06-14 02:01
Fixed by #299 and I'm going to include it in the next release before too long.

**Closed by thagikura** 2017-06-14 02:01 UTC

**Comment by stephanenicolas** [comment] 2017-06-14 04:49
Thanks. Let us know when it becomes available.

Le 13 juin 2017 19:02, "Takeshi Hagikura" <notifications@github.com> a
écrit :

**Comment by thagikura** [comment] 2017-06-16 06:08
FYI released [0.3.0-alpha4](https://github.com/google/flexbox-layout/releases/tag/0.3.0-alpha4) including this fix.

**Comment by stephanenicolas** [comment] 2017-06-16 18:43
Great thx !

2017-06-15 23:08 GMT-07:00 Takeshi Hagikura <notifications@github.com>:
