### ISSUE TITLE
too much measure

### ISSUE THREAD

**Issue by fanhongwei** [google/flexbox-layout#261] opened 2017-04-14 18:19 UTC
when flexbox parent view align-items is stretch, view visible changed will call too much measure.

**Comment by thagikura** [comment] 2017-04-17 02:00
This is duplicate of #46. Some measurements could be skipped, but basically if the attributes that are going to be relevant of deciding the size of the view,  some views have to measured multiple times.

**Closed by thagikura** 2017-04-17 02:00 UTC

**Comment by fanhongwei** [comment] 2017-04-17 15:17
@thagikura  I transformed  align-items stretch to Android view match_parent, it is faster. 
is there any potential risk？

**Comment by thagikura** [comment] 2017-04-18 02:01
If setting as match_parent meets your needs, shouldn't be a problem.

The behavior of those twos are different.
alignItems stretch -> The cross size of the views are stretched to the largest cross size in the same flex line.
match_parent -> Fit to the parent size.

**Comment by fanhongwei** [comment] 2017-04-18 03:00
@thagikura I know the different between  alignitems-stretch and match_parent， there is a bug of flexbox-layout，when parent is align-items stretch and child set width or height，CSS Flex will use child own width or height, but flexbox-layout will use align-items stretch。

**Comment by thagikura** [comment] 2017-04-18 04:11
Ok, confirmed that there is a difference with the CSS spec with that behavior.
That is different from this issue. Is it possible to file a bug for that?

**Comment by fanhongwei** [comment] 2017-04-18 05:28
done

**Comment by thagikura** [comment] 2017-04-18 05:29
Thanks!
