### ISSUE TITLE
FlexDirection.ROW is not working for FlexboxLayoutManager

### ISSUE THREAD

**Issue by bogdanzurac** [google/flexbox-layout#208] opened 2017-02-24 11:34 UTC
I'm using the new FlexboxLayoutManager with RecyclerViews children (with a common RecycledViewPool) inside a parent RecyclerView.

The main problem is that, while FlexDirection.COLUMN appears to be working just fine and lays out the Flexbox children vertically, FlexDirection.ROW doesn't work at all, no child is being drawn, in any direction whatsoever. Do you have any idea what could be wrong or any insight as to where I should start looking?

The other, rather smaller problem, is that the common RecycledViewPool doesn't appear to be... recycling the Flexbox children, among the multiple RecyclerViews. I'm not sure if this could be an issue related to the FlexboxLayoutManager or not.

**Comment by thagikura** [comment] 2017-02-24 11:49
The demo app in [demo-cat-gallery](https://github.com/google/flexbox-layout/tree/dev_recyclerview/demo-cat-gallery) uses FlexDirection.ROW.
So I guess it's caused by another reason.
Do you happen to wrap the RecyclerView with ScrollView? There is another issue (#199) that causes no items are shown in RecyclerView if you wrap it with ScrollView on API level 22 or lower.

For the latter one, could you elaborate it more?

**Comment by bogdanzurac** [comment] 2017-02-24 12:11
Well, like I said, there's a parent RecyclerView with each child containing another RecyclerView (this inner one has FlexboxLayoutManager). I'm not sure this would be the issue, considering the FlexDirection.COLUMN works. Also, I'm testing on API 25.

Here's a reference screenshot of how the layout should look like, when it was using the FlexboxLayout instead of the new FlexboxLayoutManager + RecyclerView.

![screenshot_2017-02-24-14-00-50](https://cloud.githubusercontent.com/assets/3236878/23303123/e2e2f2ce-fa9a-11e6-829b-b4e7c56b4df1.png)

**Comment by bogdanzurac** [comment] 2017-02-24 12:34
Huh, I've found the issue. The inner RecyclerViews have their height set as wrap_content. If I set this to a fixed value (100dp for example), the Flexbox children appear with FlexDirection.ROW as they should. Doesn't the FlexboxLayoutManager have AutoMeasure set to true or take its value into account?

**Comment by dammyAby** [comment] 2017-03-01 09:00
Hi @thagikura FlexBox only works for my RecyclerView when a fixed value is being set meanwhile I can pre-determine a fixed size for it. **android:layout_height="wrap_content"** makes the recyclerView items invisible.

**Comment by sagar15795** [comment] 2017-03-11 17:24
Hi @thagikura Is it fixed or any solution ?

**Comment by bogdanzurac** [comment] 2017-03-11 18:13
For the record, I've went ahead and switched back to the old FlexboxLayout method and manually created a pool of views from which the FlexboxLayout can get it's children. Works like a charm.

Should still look into the 2 issues present in the FlexboxLayoutManager:

1) ROW flex direction in combination with wrap_content
2) RecycledViewPool not recycling the FlexboxLayoutManager children.

**Comment by thagikura** [comment] 2017-03-14 00:01
Hi @sagar15795, @bogdanzurac 

Thanks for the update and sorry for not being able to address the issue.
I didn't have much time working on the FlexboxLayout lately, but I promise I get back to this one not so long. 
Thanks for your patience.

**Comment by thagikura** [comment] 2017-03-24 11:24
The first issue that `wrap_content` didn't work with `FlexDirection == ROW` should be fixed by #235.
Actually the issue seemed to happen with nested RecyclerViews.

The fix for the second issue coming soon.

**Comment by thagikura** [comment] 2017-03-30 06:20
This should be fixed by #235 and #239.

**Closed by thagikura** 2017-03-30 06:20 UTC
Labels: bug

**Comment by sagar15795** [comment] 2017-03-30 06:56
@thagikura 
Thanks for fixing it
