### ISSUE TITLE
How to use showDivider feature in FlexboxLayoutManager?

### ISSUE THREAD

**Issue by rexih** [google/flexbox-layout#246] opened 2017-04-04 09:20 UTC
RecyclerView integration had metion that it support Divider,but not find introduction .

it seems to use FlexboxItemDecoration, however it seems just set divider width and height.don't know how to set attr like middle/begin/end .and when i use the FlexboxItemDecoration ,in some phone ,has the wrong size and layout.
![wrong](https://cloud.githubusercontent.com/assets/10796628/24649839/ee576872-195a-11e7-8bda-2b80193d30c7.jpg)

**Comment by thagikura** [comment] 2017-04-04 10:41
The built-in FlexboxItemDecoration doesn't support specifying begin/middle/end configurations unlike the divider that FlexboxLayout has.
But you can extend/create a modified version of an ItemDecoration class to support the begin/middle/end variation.

For the latter part, could you share the relevant piece of your code with your issue?
Thanks.

**Comment by rexih** [comment] 2017-04-05 03:40
` 
// i use nested RecyclerView.inner is flexbox
class ViewHolder extends RecyclerView.ViewHolder {
        public SKUValueAdapter adapter;
        public TextView        tv_item_sku_attr_label;
        public RecyclerView    rv_item_sku_attr_values;

        public ViewHolder(View itemView) {
            super(itemView);
            this.tv_item_sku_attr_label = (TextView) itemView.findViewById(R.id
                    .tv_item_sku_attr_label);
            this.rv_item_sku_attr_values = (RecyclerView) itemView.findViewById(R
                    .id.rv_item_sku_attr_values);
            adapter = new SKUValueAdapter(context);
            FlexboxLayoutManager manager = new FlexboxLayoutManager();
            manager.setFlexDirection(FlexDirection.ROW);
            manager.setFlexWrap(FlexWrap.WRAP);
            manager.setJustifyContent(JustifyContent.FLEX_START);
            manager.setAlignItems(AlignItems.STRETCH);
            FlexboxItemDecoration decor = new FlexboxItemDecoration(context);
            decor.setDrawable(ApplicationContext.getDrawable(R.drawable.shape_divider_flexbox));
            decor.setOrientation(FlexboxItemDecoration.BOTH);
            rv_item_sku_attr_values.addItemDecoration(decor);

            manager.setAutoMeasureEnabled(true);
            rv_item_sku_attr_values.setHasFixedSize(true);
            rv_item_sku_attr_values.setNestedScrollingEnabled(false);
            rv_item_sku_attr_values.setLayoutManager(manager);
            rv_item_sku_attr_values.setAdapter(adapter);
        }
    }

// outside recyclerview item's layout
<?xml version="1.0" encoding="utf-8"?>
<LinearLayout
    xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="wrap_content"
    android:orientation="vertical">

    <TextView
        android:id="@+id/tv_item_sku_attr_label"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_marginBottom="20dp"
        android:textColor="@color/pos_text_main"
        android:textSize="15sp"
        tools:text="select XX"/>

    <android.support.v7.widget.RecyclerView
        android:id="@+id/rv_item_sku_attr_values"
        android:layout_width="match_parent"
        android:layout_height="wrap_content">

    </android.support.v7.widget.RecyclerView>

</LinearLayout>

//inner recyclerView item layout
<?xml version="1.0" encoding="utf-8"?>
<LinearLayout
    xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="wrap_content"
    android:layout_height="wrap_content">
    <TextView
        android:layout_marginRight="15dp"
        android:layout_marginBottom="10dp"
        android:id="@+id/tv_item_sku_value_label"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:background="@drawable/selector_bg_sku_item"
        android:enabled="true"
        android:gravity="center"
        android:minWidth="94dp"
        android:paddingBottom="5dp"
        android:paddingLeft="20dp"
        android:paddingRight="20dp"
        android:paddingTop="5dp"
        android:textColor="@drawable/selector_text_sku_item"
        android:textSize="15sp"
        tools:text="Blue"/>

</LinearLayout>

inner adaper has no affect

`

**Comment by rexih** [comment] 2017-04-05 03:42
//inner recyclerView item layout

<?xml version="1.0" encoding="utf-8"?>
<LinearLayout
    xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="wrap_content"
    android:layout_height="wrap_content">
    <TextView
        android:layout_marginRight="15dp"
        android:layout_marginBottom="10dp"
        android:id="@+id/tv_item_sku_value_label"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:background="@drawable/selector_bg_sku_item"
        android:enabled="true"
        android:gravity="center"
        android:minWidth="94dp"
        android:paddingBottom="5dp"
        android:paddingLeft="20dp"
        android:paddingRight="20dp"
        android:paddingTop="5dp"
        android:textColor="@drawable/selector_text_sku_item"
        android:textSize="15sp"
        tools:text="Blue"/>

</LinearLayout>

inner adaper has no affect

**Comment by thagikura** [comment] 2017-04-12 02:20
Sorry for the delayed comment.
It's still difficult to debug from the given information.

Is it possible to create a sample project that I can build and debug?

**Comment by thagikura** [comment] 2017-06-14 04:59
I believe this is  a duplicate of #285, so should be fixed by now.
I'm going to release a new version before too long (probably 0.3.0-alpha4)

**Closed by thagikura** 2017-06-14 04:59 UTC
