### ISSUE TITLE
Items not displaying correctly

### ISSUE THREAD

**Issue by janicelco** [google/flexbox-layout#248] opened 2017-04-05 03:40 UTC
I am using FlexboxLayout for my sorting and filtering options. I noticed that on some items with a long text, they display wrongly. ie, the last character is on the next line. See attached. Any solution for this?

Also, i have to use "middle|end" for app:showDividerVertical as "middle" alone shows on the middle items per row. So if i have 3 rows, the last item of the first 2 rows will not have the divider line showing. Unlike CSS, middle would me all elements except the last. 

`<com.google.android.flexbox.FlexboxLayout
                android:id="@+id/layout_sort_options"
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                app:flexWrap="wrap"
                app:flexDirection="row"
                app:alignItems="flex_start"
                app:alignContent="flex_start"
                app:showDividerVertical="middle|end"
                app:dividerDrawableVertical="@drawable/ic_divider"
                app:showDividerHorizontal="middle"
                app:dividerDrawableHorizontal="@drawable/ic_divider_horizontal"/>`

![flexboxerror](https://cloud.githubusercontent.com/assets/23180161/24688673/033ae0f4-19f4-11e7-9ccc-3368e8b49cdd.png)

**Comment by thagikura** [comment] 2017-04-05 04:41
What happens if you set `android:maxLines="1"` to each TextView?

For the latter part, it looks like it's the intended behavior.
> app:showDividerVertical as "middle" alone shows on the middle items per row. So if i have 3 rows, the last item of the first 2 rows will not have the divider line showing

**Comment by janicelco** [comment] 2017-04-05 04:59
When i set `textView.setMaxLines(1);` The word 'Salon' is cut off. And 'r' is missing from Hairdresser.

**Comment by thagikura** [comment] 2017-04-05 05:34
Ok, could you share other attributes for the child TextView?

**Comment by janicelco** [comment] 2017-04-05 05:37
`TextView textView = new TextView(this);
        textView.setText(text);
        textView.setId(id);
        textView.setTag(data);
        //textView.setMaxLines(1);
        textView.setSingleLine(true);
        if (Build.VERSION.SDK_INT < Build.VERSION_CODES.M)
                textView.setTextAppearance(this, R.style.StoreSortText);
        else
                textView.setTextAppearance(R.style.StoreSortText);
        textView.setOnClickListener(this);`

**Comment by thagikura** [comment] 2017-04-05 06:28
What values are set to  layout_width and layout_height?

**Comment by janicelco** [comment] 2017-04-05 06:52
It doesn't seem to have been set. Should i set it to wrap_content?

**Comment by thagikura** [comment] 2017-04-05 07:04
What happens if you set wrap_content?

By the way obviously it's not the issue with the FlexboxLayout, but how you configure the TextView.
Let me close this.

**Closed by thagikura** 2017-04-05 07:04 UTC

**Comment by janicelco** [comment] 2017-04-05 07:18
Adding this made no difference.
```
<style name="StoreSortText">
        <item name="android:textSize">15sp</item>
        <item name="android:textStyle">normal</item>
        <item name="android:textColor">@color/colorPrimaryDark</item>
        <item name="android:layout_width">wrap_content</item>
        <item name="android:layout_height">wrap_content</item>
    </style>
```

Doing it programmatically also made no difference:
```
LinearLayout.LayoutParams params = new LinearLayout.LayoutParams(LinearLayout.LayoutParams.WRAP_CONTENT,
                LinearLayout.LayoutParams.WRAP_CONTENT);
```
Tried with RelativeLayout.LayoutParams too

**Comment by janicelco** [comment] 2017-04-11 01:38
For others who encounter this issue: change the layout_width to `wrap_content`.

```
<style name="flexboxSortFilter">
        <item name="android:layout_width">wrap_content</item>
        <item name="android:layout_height">wrap_content</item>
        <item name="flexWrap">wrap</item>
        <item name="flexDirection">row</item>
        <item name="alignItems">flex_start</item>
        <item name="alignContent">flex_start</item>
        <item name="justifyContent">flex_start</item>
        <item name="showDividerVertical">middle|end</item>
        <item name="dividerDrawableVertical">@drawable/ic_divider</item>
        <item name="showDividerHorizontal">middle</item>
        <item name="dividerDrawableHorizontal">@drawable/ic_divider_horizontal</item>
    </style>
```

**Comment by Mao-x-w** [comment] 2017-04-23 04:51
I met the same problem。Thank you for your answer,it solve my problem。I tried to set  the layout_width to wrap_content,but,it doesn't work,so,I tyied to set `app:showDivider="middle"to`  `app:showDividerHorizontal="middle"app:showDividerVertical="middle|end"`as you show，it works.Thank you very    @janicelco

**Comment by huynguyennovem** [comment] 2019-09-11 16:44
Hi, although I have tried @janicelco  and @Mao-x-w  solution, it does not work. Does anyone have solution?

**Comment by shenguojun** [comment] 2024-02-04 01:32
I find the trick is setting text view with  android:maxLines="1" and android:ellipsize="none".

For those need ellipsize="end", we can add viewTreeObserver to add wrap_before dynamically.
```kotlin
viewTreeObserver.addOnGlobalLayoutListener(object : ViewTreeObserver.OnGlobalLayoutListener {
    override fun onGlobalLayout() {
        val layout = layout ?: return
        if (layout.lineCount > 0 && layout.getEllipsisCount(layout.lineCount - 1) > 0) {
            updateLayoutParams<FlexboxLayout.LayoutParams> { 
                isWrapBefore = true
            }
        }
        viewTreeObserver.removeOnGlobalLayoutListener(this)
    }
})
```
