### ISSUE TITLE
Could not find dependency "com.google.android:flexbox:1.0.0"

### ISSUE THREAD

**Issue by arash-brz** [google/flexbox-layout#477] opened 2018-12-10 16:55 UTC
I have this code(  implementation 'com.google.android:flexbox:1.0.0') in my gradle.
but when i press sync now, i faced this error in project build:
Failed to resolve: com.google.android:flexbox:1.0.0
Install Repository and sync project
Show in File
Show in Project Structure dialog
and I click  Install Repository and sync project.
progressbar starts,after a few seconds this error coming up:
Could not find dependency "com.google.android:flexbox:1.0.0"
i searched all the web and other issues but no solution founds.

**Comment by milosmns** [comment] 2018-12-10 17:58
Unfortunately you seem to have deleted the pre-filled text without reading it first, and thus didn't see that it is a requirement to check if there is a duplicate of your issue. Luckily, it's literally the top-most issue in the list: https://github.com/google/flexbox-layout/issues/475

Let's close this to avoid misdirection for other people.

**Comment by HJaliliani** [comment] 2018-12-11 08:05
It has been solved, here : [https://github.com/stfalcon-studio/ChatKit/issues/234#issuecomment-446088951](url)

**Comment by milosmns** [comment] 2018-12-11 08:43
This is the proposed workaround by maintainers in the original issue #475.

**Comment by Zeyad-37** [comment] 2018-12-11 09:51
maven {
    url "https://google.bintray.com/flexbox-layout"
}

**Comment by HJaliliani** [comment] 2018-12-11 13:09
> > I solved this , here : [https://github.com/stfalcon-studio/ChatKit/issues/234#issuecomment-446088951](url)
> 
> this link does not take me anywhere meaningful

Link is working now :) sorry

**Comment by arash-brz** [comment] 2018-12-11 17:32
thanks ,problem solved
but i lost one day for this problem.

**Closed** 2018-12-11 17:32 UTC
