### ISSUE TITLE
Scrolling problems when using minHeight in FlexboxLayoutManager 

### ISSUE THREAD

**Issue by n-apps** [google/flexbox-layout#254] opened 2017-04-11 20:58 UTC
Hi. I have been using 0.3.0-alpha3 version with RecyclerView support.

My purpose is to use full stretch with **no_wrap** for recyclerview items but when they will be shrinked <= some constant height I want to use this constant as fixed height and be able to scroll items list down.

But when I using this settings for flexbox and provide **minHeight** for recyclerview items - I just can't normally scroll down. You can scroll vertically for next item, but it will take a while.

`Flex Direction - Column`
`Flex Wrap - Nowrap`
`Justify Content - Flex Start`
`Align Items - Stretch`
`Flex Grow - 1`
`Item width and height  - -1 (match_parent)`
`Item min height - 500`

I was able to repeat the same behavior in Flexbox Playground app.

Is this intended behaviour? If so, is there a way to combine this flexbox parameters to achieve desired behaviour?

**Comment by thagikura** [comment] 2017-04-12 08:08
Hi, thanks for reporting this.

Currently if you set the flexDirection as column, the RecyclerView only scrolls horizontally.
(Vertical scroll is not supported with flexDirection is set to column or column_reverse.

But it's on the roadmap to support that.
There is another issue #215 to support that (the issue says horizontal scroll when flexDirection is row, but it's the same thing).

For the time being, I think you can achieve the same thing by using FlexboxLayout wrapped with ScrollView. But keep in mind that it doesn't recycle the Views out of the screen, so please have limited number of items in the FlexboxLayout.

Let me close this as it's duplicate of #215.

**Closed by thagikura** 2017-04-12 08:08 UTC
