### ISSUE TITLE
NullPointerException

### ISSUE THREAD

**Issue by zhangxu1005** [google/flexbox-layout#222] opened 2017-03-10 08:54 UTC
Frequently call addview() and removeAllViews().

java.lang.NullPointerException
	at com.google.android.flexbox.FlexboxLayout.drawDividersHorizontal(FlexboxLayout.java:2095)
	at com.google.android.flexbox.FlexboxLayout.onDraw(FlexboxLayout.java:2047)
	at android.view.View.draw(View.java:15114)
	at android.view.View.updateDisplayListIfDirty(View.java:14048)
	at android.view.View.getDisplayList(View.java:14071)
	at android.view.View.draw(View.java:14838)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3404)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3198)
	at android.view.View.updateDisplayListIfDirty(View.java:14043)
	at android.view.View.getDisplayList(View.java:14071)
	at android.view.View.draw(View.java:14838)

**Comment by thagikura** [comment] 2017-03-10 09:12
Thank you for reporting this. Looks like something unexpeted happened with a divider. Could you tell me how you set your divider? (Either XML or Java code)

**Comment by zhangxu1005** [comment] 2017-03-10 09:17
app:dividerDrawableHorizontal="@drawable/flex_divider"
app:dividerDrawableVertical="@drawable/flex_divider"

flex_divider.xml
<shape xmlns:android="http://schemas.android.com/apk/res/android">
    <size
        android:width="@dimen/flex_divider_width"
        android:height="@dimen/flex_divider_height" />
    <solid android:color="@android:color/transparent" />
</shape>

**Comment by zhangxu1005** [comment] 2017-03-10 09:20
`
app:dividerDrawableHorizontal="@drawable/flex_divider"
app:dividerDrawableVertical="@drawable/flex_divider"
`


flex_divider.xml
`
<shape xmlns:android="http://schemas.android.com/apk/res/android">
    <size
        android:width="8dp"
        android:height="10dp" />
    <solid android:color="@android:color/transparent" />
</shape>
`

**Comment by thagikura** [comment] 2017-03-10 14:44
Thanks. What is your `showDivider` setting? (or `showDividerHorizontal` or `showDividerVertical`)

**Comment by zhangxu1005** [comment] 2017-03-13 09:40
I do not set showDivider setting, may be I should set "none"?

**Comment by thagikura** [comment] 2017-03-13 14:16
In what orientation, you want to show your divider? 

If you set `none` it means no dividers will be drawn. So setting the dividerDrawable isn't useful.
To show a divider at least you need to set one of the `showDivider` , `showDividerHorizontal`,  `showDividerVertical`.

**Comment by zhangxu1005** [comment] 2017-03-15 02:49
Sorry , I missed sth, I do not set `showDivider` , but I have set `showDividerHorizontal` and `app:showDividerVertical`

` app:showDividerHorizontal="middle"
   app:showDividerVertical="middle"
`

**Comment by thagikura** [comment] 2017-03-21 06:02
`showDivider` is a shorthand for setting `showDividerHorizontal` and `showDividerVertical` at the same time. 
So it's totally valid if you set `showDividerHorizontal` and `showDividerVertical` separately.

However I couldn't reproduce the issue even if I called addView and removeAllViews extensively.

What version of the FlexboxLayout do you use? Current latest stable version is 0.2.5.

**Comment by zhangxu1005** [comment] 2017-03-21 08:50
I made the sample ,  please check it , https://github.com/zhangxu1005/flexbox_test.git

**Comment by thagikura** [comment] 2017-03-22 02:10
Thank you very much for the sample code.
Hmm, but I still couldn't reproduce the issue with the sample.

Could you tell me what operations are needed to reproduce if it's consistently happening?

**Comment by zhangxu1005** [comment] 2017-03-22 04:04
Sorry, I do not make the operations clear, please repeatedly click the "click here" quickly will reproduce the issues.

**Comment by thagikura** [comment] 2017-03-22 05:41
Ok I was able to reproduce the issue, thanks.

Actually the issue was already fixed in the master by #163, but not released as a library.
I'm going to release a new version anytime soon.

Thanks for reporting this!

**Closed by thagikura** 2017-03-22 05:41 UTC

**Comment by zhangxu1005** [comment] 2017-03-22 06:02
Thank you so much!

**Comment by thagikura** [comment] 2017-03-22 06:15
FYI, released a new version as 0.2.6.
The issue should be fixed.
