### ISSUE TITLE
Not wrapping content

### ISSUE THREAD

**Issue by pratikbutani** [google/flexbox-layout#80] opened 2016-06-13 11:02 UTC
As per [question on Stackoverflow ](http://stackoverflow.com/questions/37787665/android-flexbox-not-wrapping-content)Flexbox shrinks the content. Expected outcome was that, lets say, if just three categories only could be fitted in first, then, next items should appear in next line.

![image](https://cloud.githubusercontent.com/assets/3306366/16005332/5435b38e-3184-11e6-97e2-9eab1b73f74f.png)

Any help would be appreciated. Thank you.

**Comment by thagikura** [comment] 2016-06-13 11:15
Umm, if you set the `flex_wrap` attribute as `wrap`, the content will be wrapped if a new view doesn't fit in the current line.

But could you try setting the `flexShrink` in the `FlexboxLayout.LayoutParams` to 0 for each child view to see how it goes?
It will prevent each child from being shrank at all.

**Comment by thagikura** [comment] 2016-06-13 11:17
Also what version of the FlexboxLayout are you using?

**Comment by chintansoni202** [comment] 2016-06-13 11:19
I am using 0.2.2 version of Flexbox.

**Comment by thagikura** [comment] 2016-06-13 13:22
Thanks.

Could you confirm also the first question?
> But could you try setting the flexShrink in the FlexboxLayout.LayoutParams to 0 for each child view to see how it goes?
It will prevent each child from being shrank at all.


Plus, let me ask you another question.
From looking at the image you pasted, the labels seems neither being wrapped nor shrank. (It looks like the labels seem to fit in the first line)
Could you paste another screenshot with adding another label so that labels would be wrapped (or shrank)?

**Comment by thagikura** [comment] 2016-06-17 06:25
Hi, any updates on this one?

Is the issue still persistent?

**Comment by chintansoni202** [comment] 2016-06-17 07:28
Hello @thagikura I was able to solve the issue but I am not able to reproduce it.You can close the issue. Still if i encounter in future, I will definitely let you know. Thanks for your guidance.

**Comment by thagikura** [comment] 2016-06-17 07:29
Ok, thanks for the update.

**Closed by thagikura** 2016-06-17 07:29 UTC
