### ISSUE TITLE
Decoration is missing in RecyclerView when I using FlexboxLayoutManager

### ISSUE THREAD

**Issue by Cloudpoet** [google/flexbox-layout#285] opened 2017-05-20 07:03 UTC
I use FlexboxLayoutManager and FlexboxItemDecoration in my project. And there is only one RecyclerView in my activity.
It's ok when I added a item in RecyclerView if the view's height is less than screen's. But if the view's height is more than screen's, the decoration is missing in some items.
I don't know how to fix it.

**Comment by thagikura** [comment] 2017-05-25 06:02
Hi @Cloudpoet,

Thanks for reporting this, I tried to reproduce it on my end, but couldn't reproduce it so far even though I set   the ViewHolder's height longer than the screen height.

Is it possible to share your reproducible code?
Thanks.

**Comment by Cloudpoet** [comment] 2017-06-07 02:40
OK, I'll push my code to github after some time. Now I fix this problem by using margin instead of decoration

**Comment by Cloudpoet** [comment] 2017-06-07 15:05
This is the URL: 
[My demo](https://github.com/Cloudpoet/FlexDemo).
You'll see this problem if you add enough items then the height of the recyclerview is more than screen's.

**Comment by thagikura** [comment] 2017-06-08 09:30
Hi @Cloudpoet,

Thanks for the demo project! Now I can reproduce the issue.
Taking a look. Thanks!

**Comment by thagikura** [comment] 2017-06-09 08:57
Should be fixed by #294

**Closed by thagikura** 2017-06-09 08:57 UTC
Labels: bug
