### ISSUE TITLE
RecyclerView Height issue

### ISSUE THREAD

**Issue by rahuldevanavar91** [google/flexbox-layout#286] opened 2017-05-25 08:14 UTC
Hi 
  I am using RecyclerView with FlexboxLayoutManager for                  `layoutManager.setFlexDirection(FlexDirection.ROW);`
RecyclerView height is resctrited to show only 3 rows .
this is my layout 
`<RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="match_parent"
    android:layout_height="wrap_content"
    android:background="@color/white"
    android:paddingTop="@dimen/_25dp">

    <TextView
        android:id="@+id/reviews_label"
        style="@style/body1"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_marginLeft="@dimen/_10dp"
        android:text="Reviews"
        android:textAllCaps="true"
        android:textColor="@color/dark_gray_color" />

 
    <TextView
        android:id="@+id/rating_count"
        style="@style/caption"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_below="@id/reviews_label"
        android:layout_marginLeft="@dimen/_10dp"
        android:layout_marginTop="@dimen/_20dp"
        android:layout_toRightOf="@id/rating_layout"
        android:text="Based on 150 ratings"
        android:textColor="@color/dark_gray_color" />

    <TextView
        style="@style/small2"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_below="@id/rating_count"
        android:layout_marginLeft="@dimen/_10dp"
        android:layout_marginTop="@dimen/_1dp"
        android:layout_toRightOf="@id/rating_layout"
        android:text="Weighted average based on user credibility on purplle" />

    <TextView
        android:id="@+id/pros_label"
        style="@style/caption"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_below="@id/rating_layout"
        android:layout_marginBottom="@dimen/_10dp"
        android:layout_marginLeft="@dimen/_10dp"
        android:layout_marginTop="@dimen/_20dp"
        android:text="@string/positives"
        android:textColor="@color/forest_green" />

    <TextView
        android:id="@+id/tap_to_filter_pros"
        style="@style/small2"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_below="@id/rating_layout"
        android:layout_marginLeft="@dimen/_10dp"
        android:layout_marginTop="@dimen/_22dp"
        android:layout_toRightOf="@id/pros_label"
        android:text="@string/tap_to_filter"
        android:textColor="@color/light_gray_color" />

    <android.support.v7.widget.RecyclerView
        android:id="@+id/pros_highlight_recyclerview"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_below="@id/pros_label"
        android:layout_marginLeft="@dimen/_5dp"
        android:nestedScrollingEnabled="false" />
`

This is RecyclerView item layout 
```
<com.google.android.flexbox.FlexboxLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:id="@+id/highlight_root"
    android:layout_width="wrap_content"
    android:layout_height="wrap_content"
    android:layout_margin="@dimen/_5dp">

    <TextView
        android:id="@+id/selected_icon"
        style="@style/icon"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_marginRight="@dimen/_2dp"
        android:gravity="center"
        android:paddingLeft="@dimen/_5dp"
        android:text="@string/circular_tickbox"
        android:textSize="@dimen/_13dp" />

    <TextView
        android:id="@+id/name"
        style="@style/small"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_gravity="center"
        android:gravity="center"
        android:paddingBottom="@dimen/_6dp"
        android:paddingRight="@dimen/_13dp"
        android:paddingTop="@dimen/_6dp" />

</com.google.android.flexbox.FlexboxLayout>
```

**Comment by thagikura** [comment] 2017-05-25 08:46
Looks like the size seems to be constrained by the parent ViewGroup of the RecyclerView.
What the parent of RecyclerView and configurations?

**Comment by rahuldevanavar91** [comment] 2017-05-25 09:26
Parent RecyclerView has LinearLayoutManager.
this is the parent  RecyclerVier layout.
`<RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:id="@+id/root"
    android:layout_width="match_parent"
    android:layout_height="wrap_content"
    android:orientation="vertical">

    <android.support.v7.widget.RecyclerView
        android:id="@+id/list"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:background="@color/white"
        android:paddingBottom="@dimen/_2dp" />

</RelativeLayout>`

**Comment by rahuldevanavar91** [comment] 2017-05-30 07:33
if I use `layoutManager.setFlexDirection(FlexDirection.COLUMN);` this works perfectly.

**Comment by rahuldevanavar91** [comment] 2017-06-05 07:13
Hi ,
 Please help me, I am not able to solve this problem .i wasted 3 days.

**Comment by thagikura** [comment] 2017-06-15 07:40
Hi,

Sorry for the delayed reply. It looks like this is highly likely a duplicate of this #290.
If so, the issue should be fixed by now.

I'm going to release a new version anytime soon, or if you'd like to check soon, you can fetch and build the latest code from the dev_recyclerview branch.

Please reopen if this issue still persists.

Thanks.

**Closed by thagikura** 2017-06-15 07:41 UTC

**Comment by rahuldevanavar91** [comment] 2017-06-16 10:42
after upgrading to alph4  app is crashing due to                                                                     `java.lang.NoClassDefFoundError: com.google.android.flexbox.FlexboxLayoutManager
`

**Comment by thagikura** [comment] 2017-06-16 11:03
The constructor signature has changed, it now requires a Context, can you please change the part that creates it?

**Comment by rahuldevanavar91** [comment] 2017-06-16 11:07
Yes I am passing context like            
` holder.recyclerView.setLayoutManager(new FlexboxLayoutManager(mContext));
`

**Comment by thagikura** [comment] 2017-06-16 11:15
I just tried it using the alpha4 and it worked fine. Please remove the previous build cache and start from the clean state.

**Comment by rahuldevanavar91** [comment] 2017-06-16 12:19
not help, still same issue

**Comment by thagikura** [comment] 2017-06-16 14:36
Can you share your project code?

**Comment by rahuldevanavar91** [comment] 2017-06-17 06:33
sorry, i can't share the project.

**Comment by rahuldevanavar91** [comment] 2017-06-19 10:30
I got why my app is crashing because of my support library version is 23.4.0.
 if I move to 25 it won't crash .

**Comment by thagikura** [comment] 2017-06-20 00:13
Thanks for the update.

**Comment by rahuldevanavar91** [comment] 2017-06-20 06:28
any solution to run on support library version 23

**Comment by thagikura** [comment] 2017-06-20 06:31
Exclude dependency for the support library from flexbox layout.

**Comment by rahuldevanavar91** [comment] 2017-06-20 06:51
Yes I excluded, 
```
compile('com.google.android:flexbox:0.3.0-alpha4') {
        transitive = false
        exclude module: 'support-v4'
    }
```

now the app is crashing.
