### ISSUE TITLE
Scrolling problem with Header

### ISSUE THREAD

**Issue by blackvirus** [google/flexbox-layout#229] opened 2017-03-20 09:22 UTC
When  I scroll bottom, Header of recycleview is  disappeared

**Comment by thagikura** [comment] 2017-03-23 06:59
Thanks for reporting this.
Is this duplicate of #228?

**Comment by blackvirus** [comment] 2017-03-23 07:01
Yes, Duplicated

**Comment by thagikura** [comment] 2017-03-23 07:02
Ok, then let me close this.
I'll update the #228.

**Closed by thagikura** 2017-03-23 07:02 UTC
Labels: bug
